platform :ios, ’10.0’

target 'PSTodayNews' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'Kingfisher'
pod “SwiftyJSON”
pod 'SnapKit'
pod 'ObjectMapper'
pod "SVProgressHUD"
pod "FDFullscreenPopGesture", "~> 1.1"
pod "MJRefresh"
pod "Masonry"
pod "Validator"


end
